apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/code-server.ns.yaml
  - base/code-server.svc.yaml
  # - base/code-server.istio.yaml
  - base/code-server.pomerium.yaml
