# FIXME: Wait for ArgoCD 2.3 so we can separate the values to another file
authenticate:
  existingTLSSecret: wildcard-anhdle14-me-secret
  proxied: false

ingress:
  enabled: false

ingressController:
  enabled: false

extraEnvFrom:
  - secretRef:
      name: pomerium-idp

# TODO: Request Pomerium to allow configuration of changing the tls location.
# https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings
# extraVolumes:
#   - emptyDir:
#       medium: Memory
#     name: istio-certs
# extraVolumeMounts:
#   - mountPath: /etc/prom-certs/
#     name: istio-certs
# podAnnotations:
#   # do not intercept any inbound ports
#   traffic.sidecar.istio.io/includeInboundPorts: ""   
#   # do not intercept any outbound traffic
#   traffic.sidecar.istio.io/includeOutboundIPRanges: ""
#   # configure an env variable `OUTPUT_CERTS` to write certificates to the given folder
#   proxy.istio.io/config: |
#     proxyMetadata:
#       OUTPUT_CERTS: /etc/istio-output-certs
#   # mount the shared volume at sidecar proxy
#   sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]' 
# TODO: Then change the path of the TLS and CA here:

proxy:
  existingTLSSecret: wildcard-anhdle14-me-secret
  authenticateServiceUrl: "https://auth.int.anhdle14.me"

databroker:
  existingTLSSecret: wildcard-anhdle14-me-secret

authorize:
  existingTLSSecret: wildcard-anhdle14-me-secret

forwardAuth:
  enabled: false

extraEnv:
  JWT_CLAIMS_HEADERS: email

config:
  insecure: true
  rootDomain: int.anhdle14.me
  generateTLS: false
  routes:
    - from: https://httpbin.int.anhdle14.me
      to: http://httpbin.default.svc.cluster.local:8000
      allow_websockets: true
      allowed_domains:
        - int.anhdle14.me
      policy:
        - allow:
            and:
              - email:
                  is: anhdle14@icloud.com
    - from: https://jupyter.int.anhdle14.me
      to: http://jupyter.jupyter.svc.cluster.local
      allow_websockets: true
      allowed_domains:
        - int.anhdle14.me
      policy:
        - allow:
            and:
              - email:
                  is: anhdle14@icloud.com
    - from: https://code.int.anhdle14.me
      to: http://code-server.code-server.svc.cluster.local
      allow_websockets: true
      allowed_domains:
        - int.anhdle14.me
      policy:
        - allow:
            and:
              - email:
                  is: anhdle14@icloud.com